# Generated by Django 5.2.4 on 2025-07-16 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinica',
            name='endereco',
        ),
        migrations.AddField(
            model_name='clinica',
            name='bairro',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Bairro'),
        ),
        migrations.AddField(
            model_name='clinica',
            name='cep',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='CEP'),
        ),
        migrations.AddField(
            model_name='clinica',
            name='cidade',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='clinica',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail'),
        ),
        migrations.AddField(
            model_name='clinica',
            name='numero',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Número'),
        ),
        migrations.AddField(
            model_name='clinica',
            name='observacoes',
            field=models.TextField(blank=True, null=True, verbose_name='Observações'),
        ),
        migrations.AddField(
            model_name='clinica',
            name='rua',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Rua'),
        ),
        migrations.AddField(
            model_name='clinica',
            name='site',
            field=models.URLField(blank=True, null=True, verbose_name='Site'),
        ),
        migrations.AddField(
            model_name='clinica',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone'),
        ),
        migrations.AddField(
            model_name='clinica',
            name='uf',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='UF'),
        ),
        migrations.AlterField(
            model_name='clinica',
            name='cabecalho_documento',
            field=models.TextField(blank=True, null=True, verbose_name='Cabeçalho de documento'),
        ),
        migrations.AlterField(
            model_name='clinica',
            name='cnpj',
            field=models.CharField(max_length=18, unique=True, verbose_name='CNPJ'),
        ),
        migrations.AlterField(
            model_name='clinica',
            name='data_cadastro',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de cadastro'),
        ),
        migrations.AlterField(
            model_name='clinica',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='clinica',
            name='nome',
            field=models.CharField(max_length=255, verbose_name='Nome da clínica'),
        ),
        migrations.AlterField(
            model_name='clinica',
            name='responsavel',
            field=models.CharField(max_length=255, verbose_name='Responsável'),
        ),
        migrations.AlterField(
            model_name='clinica',
            name='rodape_documento',
            field=models.TextField(blank=True, null=True, verbose_name='Rodapé de documento'),
        ),
        migrations.AlterField(
            model_name='clinica',
            name='tema_visual',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Tema visual'),
        ),
    ]
