# Generated by Django 5.2.4 on 2025-07-16 21:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinicas', '0002_remove_clinica_endereco_clinica_bairro_clinica_cep_and_more'),
        ('pacientes', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora_inicio', models.DateTimeField()),
                ('data_hora_fim', models.DateTimeField()),
                ('status', models.CharField(choices=[('Agendada', 'Agendada'), ('Realizada', 'Realizada'), ('Cancelada', 'Cancelada'), ('Vencida', 'Vencida'), ('Em atendimento', 'Em atendimento')], default='Agendada', max_length=20)),
                ('urgencia', models.CharField(choices=[('Baixa', 'Baixa'), ('Média', 'Média'), ('Alta', 'Alta')], default='Baixa', max_length=10)),
                ('tipo', models.CharField(blank=True, max_length=30, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clinica', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultas', to='clinicas.clinica')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultas', to='pacientes.paciente')),
                ('profissional', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
