# Generated by Django 5.2.4 on 2025-07-16 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agendamentos', '0001_initial'),
        ('clinicas', '0001_initial'),
        ('pacientes', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_emissao', models.DateTimeField(auto_now_add=True)),
                ('prescricao_oculos', models.TextField(blank=True, null=True)),
                ('prescricao_lentes', models.TextField(blank=True, null=True)),
                ('anamnese', models.TextField(blank=True, null=True)),
                ('atestados', models.TextField(blank=True, null=True)),
                ('documentos', models.TextField(blank=True, null=True)),
                ('anexos', models.TextField(blank=True, null=True)),
                ('personalizacao', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('emitida', 'Emitida'), ('cancelada', 'Cancelada')], default='rascunho', max_length=20)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agendamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receitas', to='agendamentos.agendamento')),
                ('clinica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receitas', to='clinicas.clinica')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receitas', to='pacientes.paciente')),
            ],
        ),
    ]
